### ISSUE TITLE
GraphiQL using the cli won't load the mutations, but it works on the server

### ISSUE THREAD

**Issue by alansikora** [cdaringe/postgraphile-upsert#251]
Hey!

I've been trying to use this plugin on my local environment using postgraphile cli, but I've been having a hard time setting it up.

This is my rc file:

```js
module.exports = {
    options: {
        graphileBuildOptions: {
            connectionFilterRelations: true,
        },
        plugins: [
            "postgraphile-plugin-connection-filter",
            "postgraphile-upsert-plugin"
        ]
    },
};
```

For some reason, event leaving only `postgraphile-upsert-plugin` enabled, it still won't load/autocomplete upsert mutations.

When debugging, it says it was loaded:

![image](https://user-images.githubusercontent.com/575138/143011164-54ddc46e-9039-46bd-b01e-f523984a0d3a.png)

Do you know the reason this might be happening?

**Comment by cdaringe** [comment]
You might need to enable schema watching, I’m not sure

**Comment by cdaringe** [comment]
Please consult the tests. They demonstrate successful setup and consumption
