### ISSUE TITLE
Error in the docs + question

### ISSUE THREAD

**Issue by francescovenica** [cdaringe/postgraphile-upsert#483]
Hello, I think there is an error in the docs, it should be:
```
import { PgMutationUpsertPlugin } from "postgraphile-upsert-plugin";
```

not
```
import PgMutationUpsertPlugin from "postgraphile-upsert-plugin";
```

I have also a question, would be possible to implement the upsert on multiple objects? so, accept an array instead of a single object?

**Comment by cdaringe** [comment]
Hello! Thanks, feel free to send a docs patch. On bulk upserts, super open to it, but i wont be personally implementing it.

**Comment by francescovenica** [comment]
thanks for the quick feedback, I never worked on plugins with postgraphile, do you have any input on how it can be done? I'll try to dig into the code and see if i can implement something goos

**Comment by cdaringe** [comment]
ya for sure! they have a guide here: https://www.graphile.org/postgraphile/extending/
