### ISSUE TITLE
Is this plugin (already) v5 compatible?

### ISSUE THREAD

**Issue by barbalex** [cdaringe/postgraphile-upsert#646]
v5 is being pre-released. Will post if I get it to work or if I get an error referring to this plugin.

Edit: v4 Plugins do not work for v5 as they previously were functions, now they are declarative objects (https://postgraphile.org/postgraphile/next/migrating-from-v4/#plugins).

**Comment by cdaringe** [comment]
all about it, but let's visit when v5 goes public! unless you know if there's an easy way to achieve cross compat _and_ test it :)

**Comment by zackeryg** [comment]
I saw that v5 is labeled as production ready - but I don't think there is a solid way for cross compat

I took a stab at upgrading this plugin and it wasn't straight forward.

Discord link to my question to Benji:
https://discord.com/channels/489127045289476126/498852330754801666/1154174269962584164
