### ISSUE TITLE
Add `where` input argument - a new fork

### ISSUE THREAD

**Issue by jashmenn** [cdaringe/postgraphile-upsert#8]
👋 Hey! I've [forked this repo](https://github.com/jashmenn/postgraphile-upsert-plugin) and added a `where` input argument to the upsert.

As of writing, the original repo here only uses the primary key in the upsert `on conflict`, which isn't very helpful (why would you do an upsert if you already have the primary key?).

Instead, my fork allows you to use any of the unique constraints to specify the upsert condition:

## Example

```sql
create table bikes (
  id serial PRIMARY KEY,
  "serialNumber" varchar UNIQUE NOT NULL,
  weight real,
  make varchar,
  model varchar
)
```

An upsert would look like this:

```graphql
mutation {
  upsertBike(
    where: { serialNumber: "abc123" }
    input: {
      bike: {
        serialNumber: "abc123"
        weight: 25.6
        make: "kona"
        model: "cool-ie deluxe"
      }
    }
  ) {
    clientMutationId
  }
}
```

You can [find it here](https://github.com/jashmenn/postgraphile-upsert-plugin)

**Comment by cdaringe** [comment]
Ya, that sounds super useful.  Just using the pk is not entirely pragmatic

**Comment by cdaringe** [comment]
If you want to add it here I'll give you full perms.  If you don't, no sweat

**Comment by jashmenn** [comment]
Sure! I'd love a second pair of eyes on it if you have some time.

I'd be happy to merge it in here if you think it fits. We'd need a major version bump because it breaks the existing API.

**Comment by bfelbo** [comment]
This sounds great. Is it being added?

**Comment by cdaringe** [comment]
I've been super slammed and haven't had a moment to get in there. If someone wants to set up PR I will definitely review and merge quickly so long as the normal checks pass

**Comment by jashmenn** [comment]
I’m happy to merge my fork into this main branch, but I also haven’t had
the time to make a proper pull request.

If someone would like to, I’d be happy to review and unify the projects

**Comment by cdaringe** [comment]
I started this.  almost finished :)

**Comment by bfelbo** [comment]
Amazing, thanks!!

**Comment by cdaringe** [comment]
hey @jashmenn, i noticed that in your impl, `snake_cased` fields (e.g. `serial_number`) don't cleanly map back into `serialNumber` per the defacto behavior between pg fields and gql fields.  i'm a little rusty getting back into this.  know what needs to happen there?  in your tests, i'd really like to see `"serialNumber"` ==> `serial_number` in the create table sql and have it all buck.  i will look into it a bit more later as well

**Comment by jashmenn** [comment]
@cdaringe the incorrect mapping is probably a bug/oversight and something that should be fixed

**Comment by bfelbo** [comment]
What's needed to finish this? We need upsert right now and would really love to use this plugin :)

**Comment by cdaringe** [comment]
need to square https://github.com/cdaringe/postgraphile-upsert/issues/8#issuecomment-468955147 away.  merging @jashmenn's work into my fork isn't a _huge_ diff, but there a non-trivial amount of resolution at play.

it's not hot on my radar TBH, but i _do_ want it too.  if you can figure out https://github.com/cdaringe/postgraphile-upsert/issues/8#issuecomment-468955147, i will commit to getting a version bump in w/in a week of that time

**Comment by lukepatrick** [comment]
[#8 (comment)](https://github.com/cdaringe/postgraphile-upsert/issues/8#issuecomment-468955147) was fixed with PR 2 https://github.com/jashmenn/postgraphile-upsert-plugin/pull/2

**Comment by m-nny** [comment]
@cdarigne @jashmenn is there any updates?

**Comment by cdaringe** [comment]
merged
